# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
    - main
    - release/*
  pull_request:
    branches: 
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: Source
    - name: Build
      run: dotnet build --no-restore
      working-directory: Source
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Source
    - name: Publish Build Artifacts
      run: dotnet publish Solution.sln --configuration Release --output ./publish --runtime win-x64
      working-directory: Source
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: Source/publish/
